export const USUARIOS_SEED = [
  { correo: 'cesar.leal@gmail.com', nombre_completo: 'César Augusto Leal Lecaros', rut: '11485400-k', roles: 'ADMIN,COORD,TUTOR', grupos: 'A10', correo_zoom: 'zoomprofesor.ia4@ciae.uchile.cl', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'zoomprofesor.ia4@ciae.uchile.cl', nombre_completo: 'César Augusto Leal Lecaros', rut: '11485400-k', roles: 'ADMIN,COORD,TUTOR', grupos: 'A10', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'dasa36@gmail.com', nombre_completo: 'Daniel Alberto Segura Angel', rut: '13417511-7', roles: 'ADMIN,COORD', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'nenagracia@gmail.com', nombre_completo: 'María Elena Gracia Romero', rut: '8469369-3', roles: 'COORD', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'me.graciaromero@gmail.com', nombre_completo: 'María Elena Gracia Romero', rut: '8469369-3', roles: 'COORD', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'rosaeliana.romero.alonso@gmail.com', nombre_completo: 'Rosa Eliana Romero Alonso', rut: '12364868-4', roles: 'COORD', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'rera73@gmail.com', nombre_completo: 'Rosa Eliana Romero Alonso', rut: '12364868-4', roles: 'COORD', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'santiago.scabezas@gmail.com', nombre_completo: 'Santiago Alfredo Cabezas González', rut: '10890554-9', roles: 'TUTOR', grupos: 'A04,A06,A09,B16', correo_zoom: 'zoomprofesor.ia10@ciae.uchile.cl', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'orfigata@gmail.com', nombre_completo: 'María Alicia Soto Alvarez', rut: '9396172-2', roles: 'TUTOR', grupos: 'A02,B12', correo_zoom: 'zoomprofesor.ia7@ciae.uchile.cl', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'pazmagaly13@gmail.com', nombre_completo: 'Paz Magaly Lorca Peña', rut: '10697924-3', roles: 'TUTOR', grupos: 'A08,B13', correo_zoom: 'zoomprofesor.ia9@ciae.uchile.cl', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'jenharris079@gmail.com', nombre_completo: 'Jenny Karemlee Moses Harris', rut: '21872911-2', roles: 'TUTOR', grupos: 'A01,B15', correo_zoom: 'zoomprofesor.ia6@ciae.uchile.cl', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'alejandra.saez32@gmail.com', nombre_completo: 'María Alejandra Sáenz Calderón', rut: '10981908-5', roles: 'TUTOR', grupos: 'A05,A07', correo_zoom: 'zoomprofesor.ia3@ciae.uchile.cl', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'ggarrido.fisica@gmail.com', nombre_completo: 'Guillermo Hernán Garrido Acevedo', rut: '10412255-8', roles: 'TUTOR', grupos: 'B11,B14', correo_zoom: 'zoomprofesor.ia5@ciae.uchile.cl', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'patriciatabilogomez@gmail.com', nombre_completo: 'Patricia Luisa Tabilo Gómez', rut: '12239197-3', roles: 'TUTOR', grupos: 'A03', correo_zoom: 'zoomprofesor.ia8@ciae.uchile.cl', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'marjorie.araneda@gmail.com', nombre_completo: 'Marjorie Angélica Araneda Muñoz', rut: '13305951-2', roles: 'ASISTENTE', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'brandon.pichicon@gmail.com', nombre_completo: 'Brandon Alejandro Pichicon Roa', rut: '20998853-4', roles: 'ASISTENTE', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'florenciajaraarancibia@gmail.com', nombre_completo: 'Florencia Antonia Jara Arancibia', rut: '20195681-1', roles: 'ASISTENTE', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'ivan8enteros@gmail.com', nombre_completo: 'Iván Andrés Ramírez Alarcón', rut: '14408781-k', roles: 'ASISTENTE', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-03-01' },
  { correo: 'catalinazelada@gmail.com', nombre_completo: 'Catalina Zelada Carreño', rut: '17560577-0', roles: 'ASISTENTE', grupos: '', correo_zoom: '', activo: 'TRUE', fecha_creacion: '2026-05-19' },
];

export const GRUPOS_SEED = [
  { id: 'A01', tutor_correo: 'jenharris079@gmail.com', tutor_nombre: 'Jenny Karemlee Moses Harris', dia_tutoria: 'Lunes', horario_tutoria: '18:00-20:00', dia_experto: 'Miércoles', horario_experto: '19:00-21:00', tipo_establecimiento: 'ESCUELAS', pax: 25 },
  { id: 'A02', tutor_correo: 'orfigata@gmail.com', tutor_nombre: 'María Alicia Soto Alvarez', dia_tutoria: 'Lunes', horario_tutoria: '18:00-20:00', dia_experto: 'Miércoles', horario_experto: '19:00-21:00', tipo_establecimiento: 'ESCUELAS', pax: 25 },
  { id: 'A03', tutor_correo: 'patriciatabilogomez@gmail.com', tutor_nombre: 'Patricia Luisa Tabilo Gómez', dia_tutoria: 'Lunes', horario_tutoria: '19:00-21:00', dia_experto: 'Miércoles', horario_experto: '19:00-21:00', tipo_establecimiento: 'RURAL', pax: 25 },
  { id: 'A04', tutor_correo: 'santiago.scabezas@gmail.com', tutor_nombre: 'Santiago Alfredo Cabezas', dia_tutoria: 'Lunes', horario_tutoria: '20:00-22:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'LICEOS', pax: 25 },
  { id: 'A05', tutor_correo: 'alejandra.saez32@gmail.com', tutor_nombre: 'María Alejandra Sáenz Calderón', dia_tutoria: 'Lunes', horario_tutoria: '20:00-22:00', dia_experto: 'Miércoles', horario_experto: '19:00-21:00', tipo_establecimiento: 'TP/ARTES/OTROS', pax: 25 },
  { id: 'A06', tutor_correo: 'santiago.scabezas@gmail.com', tutor_nombre: 'Santiago Alfredo Cabezas', dia_tutoria: 'Lunes', horario_tutoria: '16:00-18:00', dia_experto: 'Miércoles', horario_experto: '19:00-21:00', tipo_establecimiento: 'RURAL/ADULTO', pax: 25 },
  { id: 'A07', tutor_correo: 'alejandra.saez32@gmail.com', tutor_nombre: 'María Alejandra Sáenz Calderón', dia_tutoria: 'Lunes', horario_tutoria: '18:00-20:00', dia_experto: 'Miércoles', horario_experto: '19:00-21:00', tipo_establecimiento: 'BICENTENARIOS', pax: 25 },
  { id: 'A08', tutor_correo: 'pazmagaly13@gmail.com', tutor_nombre: 'Paz Magaly Lorca Peña', dia_tutoria: 'Lunes', horario_tutoria: '18:00-20:00', dia_experto: 'Miércoles', horario_experto: '19:00-21:00', tipo_establecimiento: 'ESCUELAS', pax: 25 },
  { id: 'A09', tutor_correo: 'santiago.scabezas@gmail.com', tutor_nombre: 'Santiago Alfredo Cabezas', dia_tutoria: 'Lunes', horario_tutoria: '18:00-20:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'LICEOS', pax: 25 },
  { id: 'A10', tutor_correo: 'cesar.leal@gmail.com', tutor_nombre: 'César Augusto Leal Lecaros', dia_tutoria: 'Lunes', horario_tutoria: '20:00-22:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'TP', pax: 25 },
  { id: 'B11', tutor_correo: 'ggarrido.fisica@gmail.com', tutor_nombre: 'Guillermo Hernán Garrido', dia_tutoria: 'Martes', horario_tutoria: '18:00-20:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'ESCUELAS', pax: 25 },
  { id: 'B12', tutor_correo: 'orfigata@gmail.com', tutor_nombre: 'María Alicia Soto Alvarez', dia_tutoria: 'Martes', horario_tutoria: '18:00-20:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'COLEGIOS', pax: 25 },
  { id: 'B13', tutor_correo: 'pazmagaly13@gmail.com', tutor_nombre: 'Paz Magaly Lorca Peña', dia_tutoria: 'Martes', horario_tutoria: '18:00-20:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'ESCUELAS/PARV.', pax: 25 },
  { id: 'B14', tutor_correo: 'ggarrido.fisica@gmail.com', tutor_nombre: 'Guillermo Hernán Garrido', dia_tutoria: 'Martes', horario_tutoria: '20:00-22:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'LICEOS', pax: 25 },
  { id: 'B15', tutor_correo: 'jenharris079@gmail.com', tutor_nombre: 'Jenny Karemlee Moses Harris', dia_tutoria: 'Martes', horario_tutoria: '20:00-22:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'ESCUELAS', pax: 25 },
  { id: 'B16', tutor_correo: 'santiago.scabezas@gmail.com', tutor_nombre: 'Santiago Alfredo Cabezas', dia_tutoria: 'Martes', horario_tutoria: '20:00-22:00', dia_experto: 'Jueves', horario_experto: '19:00-21:00', tipo_establecimiento: 'ESCUELAS', pax: 25 },
];

export const CONFIG_SEED = {
  nombre_curso: 'Mejorando la Gestión Escolar con IA',
  institucion: 'CPEIP / Instituto de Educación, U. de Chile',
  anio: 2026,
  fecha_inicio: '2026-03-10',
  fecha_cierre: '2026-06-02',
  total_semanas: 12,
  hora_inicio_sesion: '20:00',
  duracion_minutos: 120,
  umbral_critico: 70,
  umbral_alerta: 75,
  umbral_justificaciones: 3,
  umbral_retiros: 3,
  umbral_dias_moodle: 7,
  umbral_logro: 60,
  umbral_evaluaciones_logro: 2,
  descuento_retiro_primera_hora: 50,
  descuento_tardanza: 100,
  setup_completo: 'FALSE',
};

export const SHEET_HEADERS = {
  CONFIGURACION: ['nombre_curso','institucion','anio','fecha_inicio','fecha_cierre','total_semanas','hora_inicio_sesion','duracion_minutos','umbral_critico','umbral_alerta','umbral_justificaciones','umbral_retiros','umbral_dias_moodle','umbral_logro','umbral_evaluaciones_logro','descuento_retiro_primera_hora','descuento_tardanza','setup_completo'],
  CALENDARIO: ['semana','tipo_sesion','fecha','descripcion'],
  USUARIOS: ['correo','nombre_completo','rut','roles','grupos','activo','correo_zoom','fecha_creacion'],
  PARTICIPANTES: ['rut','nombres','primer_apellido','segundo_apellido','nombre_completo','correo','genero','telefono','contacto_preferido','grupo','microgrupo','funcion_principal','establecimiento','tipo_establecimiento','rbd','region','comuna','dependencia','estado','fecha_ingreso','fecha_baja','motivo_baja','notas'],
  ASISTENCIA: ['id','rut_participante','grupo','semana','tipo_sesion','fecha_sesion','estado','hora_evento','pct_sesion','registrado_por','fecha_registro','editado','fecha_edicion','editado_por'],
  RESUMEN_PARTICIPANTE: ['rut','grupo','pct_asistencia','sesiones_cursadas','sesiones_asistidas','contador_j','contador_r','contador_a','alerta_asistencia','alerta_justificaciones','alerta_retiros','alerta_logro','alerta_moodle','alerta_max','ultima_sesion_registrada','fecha_ultimo_registro','logro_promedio','evaluaciones_bajo_umbral'],
  NOVEDADES: ['id','fecha_registro','semana','tipo_sesion','grupo','rut_participante','nombre_participante','tipo_novedad','hora_evento','estado_caso','requiere_seguimiento','observacion','registrado_por','fecha_edicion','editado_por'],
  MOODLE_SEMANAL: ['id','rut_participante','grupo','semana','ultimo_acceso','dias_sin_acceso','participo_foro','entrego_producto','blog_actualizado','estado_moodle','cargado_por','fecha_carga'],
  LOG: ['id','datetime','usuario','rol_activo','accion','entidad','grupo','semana','detalle','ip'],
  EVALUACIONES: ['id','rut_participante','grupo','semana','nombre_evaluacion','puntaje','bajo_umbral','registrado_por','fecha_registro'],
};
